### ISSUE TITLE
Good First Issue

### ISSUE THREAD

**Issue by arm210402** [arm210402/Tech-Website#1]
Anyone is free to raise PR on my website and make a simple contribution in tech.html

**Comment by abhie16** [comment]
hello, I would like to contribute. Pls share your goal

**Comment by arm210402** [comment]
Fork this repo and add 4-5 products along with buy option in tech.html or make a new html file

**Comment by abhie16** [comment]
ok pls assign to me for this

**Comment by arm210402** [comment]
just make a pull request

**Comment by abhie16** [comment]
![image](https://user-images.githubusercontent.com/95357648/183007170-0a27d33a-6f04-4a3c-9817-8fba28967352.png)

Is it good?

**Comment by arm210402** [comment]
Its good👍 but we need to include this in texh.html cuz for main page i have different plans

**Comment by abhie16** [comment]
it is in tech page

**Comment by arm210402** [comment]
yep  for now but after this posting it as a template so that anyone can modify and make their own edits in this code

**Comment by abhie16** [comment]
ok I m  making PR , so that you can check and comment there as your need

**Comment by arm210402** [comment]
OK will accept once checked

**Comment by arm210402** [comment]
Issue solved
